set nu
syntax on
filetype indent plugin on
set ruler

set autoindent

set modeline

" handles cut-and-paste issue
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

hi LineNr ctermfg=darkcyan ctermbg=black
colorscheme elflord
